<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '* нажимая кнопку «Отправить», я даю свое согласие на обработку моих персональных данных, в соответствии с Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных»'      => '* by clicking the "Submit" button, I give my consent to the processing of my personal data',
    'BIG DATA — НЕФТЬ НАШЕГО ВРЕМЕНИ'       => 'BIG DATA - OIL OF OUR TIME',
    'Адрес'     => 'Address',
    'В 2021 году дата-центр стремительно наращивает парк вычислительных мощностей, соответствуя всё возрастающему спросу на дата центры. Открыты возможности совместных вложений в оборудование. Специалисты центра помогут сделать выбор и возьмут все заботы на себя.'        => 'In 2021 our data center is rapidly expanding its computing power park due of increasing demand. We provide you opportunity to place your equipment in our facilities. Our team will help, you to make a choice and take care of all requred work.',
    'Видеонаблюдение, трансляция на смартфон владельца'     => 'CCTV, broadcast on your smartphone',
    'Вопрос'        => 'Question',
    'Всё оформляется в соответствии с законодательством РФ'     => 'All contracts in accordance with the law',
    'Высококлассная IT команда – гарантия надежности рабочих процессов'     => 'High-quality IT team is a guarantee of reliability of work processes',
    'ГАРАНТИИ'      => 'WARRANTY',
    'Гарантии'      => 'Warranty',
    'Где YouTube хранит видео, а Instagram – фотографии, сколько это весит и во сколько обходится компаниям? Кто задумывается о том, где конкретно хранятся и обрабатываются эти данные? Сейчас в мире около 50 млрд подключенных к интернету устройств. Каждый житель Земли генерирует 1,7 Мб информации в секунду и эти показатели растут с каждым днем. 30% всех данных хранится и обрабатывается в облаке. Сегодня развитие технологий идет рука об руку с ростом объема данных. И чем дальше, тем больше их будет. Речь идет о востребованных данных о поведении пользователей, Big Data, искусственном интеллекте.'       => 'Where does YouTube store videos and Instagram stores photos, how much does it weigh and how much does it cost companies? Who thinks about where exactly this data is stored and processed?, There are now about 50 billion Internet-connected devices in the world. Every human generates 1.7 MB of information per a second and these figures are growing every day. 30% of all data is stored and processed in the cloud. Today technological advances go hand in hand with data growth. Then further it go, then more it will grow. We are talking about in-demand of data of users behavior, Big Data and artificial intelligence.',
    'И вычислительных мощностей'        => 'And computing power',
    'Имя'       => 'Name',
    'Индивидуальный серийный номер, подпись полки именем владельца'     => 'Individual serial number, shelf signature with owner\'s name',
    'Кейсы'     => 'Cases',
    'Консалтинговые услуги в сфере информационных технологий'       => 'Information technology consulting services',
    'Консультация'      => 'Consultation',
    'Контакты'      => 'Contacts',
    'Мгновенный доступ к онлайн отчётности. Онлайн мониторинг'      => 'Instant access to online reports. Online monitoring',
    'Мы круглосуточно осуществляем мониторинг всех текущих процессов'       => '24 hours monitoring of all current processes',
    'Мы предлагаем'     => 'We offer',
    'Нажимая кнопку «Отправить», я даю свое согласие на обработку моих персональных данных, в соответствии с Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных», на условиях и для целей, определенных в Согласии на обработку персональных данных *'       => '* by clicking the "Submit" button, I give my consent to the processing of my personal data',
    'Наши преимущества'     => 'Our advantages',
    'Необходимость внедрения IT решений в бизнесе стремительно набирают популярность в качестве эффективных инструментов и средств менеджмента, постепенно, но уверенно становясь значимой частью каждого предприятия. Увеличение экономического влияния IT индустрии на международных рынках сопровождается уверенным ростом их капитализации, с каждым годом ставящей новые рекорды.'     => 'The need of implementation of IT solutions in business is rapidly gaining popularity as effective management tools, gradually but surely becoming an important part of every company. The, growth of economic influence in IT industry on international markets is supported by growth of capitalization and breaks records every year.',
    'О проекте'     => 'About',
    'ОСТАЛИСЬ ВОПРОСЫ?'     => 'STILL HAVE QUESTIONS?',
    'Оборудование'      => 'Equipment',
    'Оптимальная локация дата-центра в регионах с холодным  климатом, чтобы обеспечить идеальную температуру помещений для хостинга и минимизировать расходы на электроэнергию за счет естественного охлаждения оборудования'       => 'Location of data center in cold regions provides ideal temperatures on facilities and minimize energy consumption by using natural cooling of equipment',
    'Опыт успешной деятельности в IT сфере с 2017 года и долгосрочные налаженные контакты с партнерами'     => 'Successful experience in the IT field since 2017 and long-term established contacts with partners',
    'Оставьте ваши контактные данные и мы перезвоним вам в ближайшее время'     => 'Leave your contact details and we will call you back shortly',
    'Отправить'     => 'Send',
    'Партнеры со всего мира'      => '',
    'Подтверждение единицей оборудования 1:1'     => '',
    'Пожалуйста, заполните данные. Мы с вами свяжемся!'   => '',
    'Положитесь на экспертов'     => '',
    'Получить консультацию'   => '',
    'Поставка и хостинг компьютерного оборудования в дата-центрах'    => '',
    'Почта'   => '',
    'Преимущества'    => '',
    'Промышленный хостинг компьютерного оборудования и разработка цифровых решений для вашего бизнеса'    => '',
    'Прямые поставки оборудования без  посредников по оптовым ценам'      => '',
    'Разработка программного обеспечения и IT решений для Вашего бизнеса'     => '',
    'Реальная или виртуальная экскурсия по первому требованию'    => '',
    'СЕЙЧАС ЛУЧШЕЕ ВРЕМЯ ДЛЯ РОСТА ДАТА-ЦЕНТРОВ'      => '',
    'Собственные разработки и IT-решения'     => '',
    'Спасибо, ваше сообщение принято.'    => '',
    'Телефон'     => '',
    'Услуги'      => '',
    'Услуги облачных решений и аренды вычислительных мощностей для вашего бизнеса'    => '',
    'Фотофиксация всех этапов покупки и установки'    => '',
    'Хостинг компьютерного оборудования в дата-центрах'   => '',
    'ЦОД может быть предназначен как для использования одним предприятием, так и являться  многопользовательским.  Многопользовательский ЦОД предоставляет широкий спектр услуг, среди которых business continuity & disaster recovery (непрерывность бизнеса), хостинг, аренда сервера, размещение сервера и т.д. Обращение к услугам многопользовательского ЦОД наиболее целесообразно для компаний среднего и малого бизнеса, т.к. позволяет избежать капитальных затрат на модернизацию ИТ-инфрастурктуры и получить высококачественный сервис и гарантию надежности.'    => '',
    'один из крупнейших дата-центров в Восточной Сибири с мощностью свыше 5 МВт. Мы занимаемся промышленным хостингом компьютерного оборудования и разработкой IT решений для управления компьютерными сетями.'   => '',
];
